import { Recipe } from "./types";

// Recettes healthy de base, orientées pratiquant de JJB (riche en protéines,
// bon équilibre glucides/lipides, pensées pour la récup' et la gestion de poids).
export const SEED_RECIPES: Recipe[] = [
  {
    id: "seed-1",
    name: "Bowl poulet, riz complet & brocolis",
    category: "dejeuner",
    kcal: 520,
    protein: 45,
    carbs: 55,
    fat: 12,
    prepMinutes: 25,
    ingredients: [
      "150g blanc de poulet",
      "80g riz complet (poids cru)",
      "150g brocolis",
      "1 c. à s. huile d'olive",
      "Sauce soja, ail, gingembre",
    ],
    steps: [
      "Cuire le riz complet.",
      "Faire revenir le poulet coupé en dés avec ail et gingembre.",
      "Cuire les brocolis à la vapeur 5-7 min.",
      "Assembler dans un bowl, arroser de sauce soja et d'un filet d'huile d'olive.",
    ],
    favorite: false,
  },
  {
    id: "seed-2",
    name: "Porridge protéiné banane-amande",
    category: "petit-dejeuner",
    kcal: 420,
    protein: 28,
    carbs: 50,
    fat: 12,
    prepMinutes: 10,
    ingredients: [
      "50g flocons d'avoine",
      "1 scoop whey vanille",
      "1 banane",
      "200ml lait d'amande",
      "1 c. à s. beurre d'amande",
    ],
    steps: [
      "Faire chauffer le lait d'amande avec les flocons d'avoine 5 min.",
      "Retirer du feu, incorporer la whey une fois tiède.",
      "Ajouter la banane en rondelles et le beurre d'amande.",
    ],
    favorite: false,
  },
  {
    id: "seed-3",
    name: "Saumon grillé, patate douce & épinards",
    category: "diner",
    kcal: 560,
    protein: 40,
    carbs: 45,
    fat: 20,
    prepMinutes: 30,
    ingredients: [
      "150g pavé de saumon",
      "1 patate douce moyenne",
      "100g épinards frais",
      "Citron, huile d'olive, sel, poivre",
    ],
    steps: [
      "Couper la patate douce en cubes, cuire au four 25 min à 200°C.",
      "Poêler le saumon 4 min de chaque côté.",
      "Faire tomber les épinards à la poêle avec un filet d'huile.",
      "Dresser avec un trait de citron.",
    ],
    favorite: false,
  },
  {
    id: "seed-4",
    name: "Shaker de récup' post-training",
    category: "post-training",
    kcal: 280,
    protein: 30,
    carbs: 35,
    fat: 4,
    prepMinutes: 5,
    ingredients: [
      "1 scoop whey",
      "1 banane",
      "250ml lait écrémé ou boisson végétale",
      "1 pincée de sel (électrolytes)",
    ],
    steps: [
      "Mixer tous les ingrédients.",
      "Boire dans les 30-45 min après la séance.",
    ],
    favorite: false,
  },
  {
    id: "seed-5",
    name: "Œufs brouillés, avocat & pain complet",
    category: "petit-dejeuner",
    kcal: 450,
    protein: 24,
    carbs: 30,
    fat: 24,
    prepMinutes: 12,
    ingredients: [
      "3 œufs",
      "1/2 avocat",
      "2 tranches pain complet",
      "Sel, poivre, piment doux",
    ],
    steps: [
      "Brouiller les œufs à feu doux.",
      "Griller le pain, écraser l'avocat dessus.",
      "Servir ensemble, assaisonner.",
    ],
    favorite: false,
  },
  {
    id: "seed-6",
    name: "Salade thon, quinoa & pois chiches",
    category: "dejeuner",
    kcal: 490,
    protein: 35,
    carbs: 48,
    fat: 15,
    prepMinutes: 15,
    ingredients: [
      "1 boîte de thon au naturel",
      "80g quinoa (poids cru)",
      "100g pois chiches cuits",
      "Concombre, tomate, huile d'olive, citron",
    ],
    steps: [
      "Cuire le quinoa selon le paquet, laisser refroidir.",
      "Mélanger avec le thon égoutté, les pois chiches et les légumes coupés.",
      "Assaisonner avec huile d'olive et citron.",
    ],
    favorite: false,
  },
  {
    id: "seed-7",
    name: "Wrap dinde, crudités & houmous",
    category: "collation",
    kcal: 350,
    protein: 25,
    carbs: 35,
    fat: 12,
    prepMinutes: 8,
    ingredients: [
      "1 tortilla complète",
      "80g blanc de dinde tranché",
      "2 c. à s. houmous",
      "Carotte râpée, salade, concombre",
    ],
    steps: [
      "Étaler le houmous sur la tortilla.",
      "Garnir de dinde et de crudités.",
      "Rouler serré et couper en deux.",
    ],
    favorite: false,
  },
  {
    id: "seed-8",
    name: "Yaourt grec, fruits rouges & granola maison",
    category: "collation",
    kcal: 300,
    protein: 20,
    carbs: 32,
    fat: 9,
    prepMinutes: 5,
    ingredients: [
      "200g yaourt grec 0-2%",
      "100g fruits rouges (frais ou surgelés)",
      "30g granola peu sucré",
      "1 filet de miel (optionnel)",
    ],
    steps: [
      "Verser le yaourt dans un bol.",
      "Ajouter les fruits rouges et le granola.",
      "Filet de miel en option.",
    ],
    favorite: false,
  },
  {
    id: "seed-9",
    name: "Curry de lentilles corail & riz basmati",
    category: "diner",
    kcal: 480,
    protein: 22,
    carbs: 70,
    fat: 12,
    prepMinutes: 30,
    ingredients: [
      "150g lentilles corail",
      "70g riz basmati (poids cru)",
      "Lait de coco léger, curry, oignon, ail",
      "Épinards ou tomates",
    ],
    steps: [
      "Faire revenir oignon et ail, ajouter le curry.",
      "Ajouter les lentilles, le lait de coco et un peu d'eau, cuire 20 min.",
      "Servir avec le riz basmati cuit.",
    ],
    favorite: false,
  },
  {
    id: "seed-10",
    name: "Omelette blanche aux légumes",
    category: "post-training",
    kcal: 310,
    protein: 32,
    carbs: 12,
    fat: 14,
    prepMinutes: 12,
    ingredients: [
      "5 blancs d'œufs + 1 œuf entier",
      "Poivron, champignons, épinards",
      "1 c. à c. huile d'olive",
    ],
    steps: [
      "Faire revenir les légumes émincés.",
      "Ajouter les œufs battus, cuire à feu doux en pliant l'omelette.",
    ],
    favorite: false,
  },
  {
    id: "seed-11",
    name: "Skyr, flocons d'avoine & myrtilles",
    category: "petit-dejeuner",
    kcal: 380,
    protein: 26,
    carbs: 45,
    fat: 8,
    prepMinutes: 5,
    ingredients: [
      "200g skyr nature",
      "40g flocons d'avoine",
      "80g myrtilles fraîches ou surgelées",
      "1 c. à c. graines de chia",
    ],
    steps: [
      "Mélanger le skyr et les flocons d'avoine.",
      "Laisser gonfler 5-10 min (ou toute la nuit au frigo).",
      "Ajouter les myrtilles et les graines de chia avant de servir.",
    ],
    favorite: false,
  },
  {
    id: "seed-12",
    name: "Toasts à l'œuf poché et saumon fumé",
    category: "petit-dejeuner",
    kcal: 410,
    protein: 27,
    carbs: 28,
    fat: 20,
    prepMinutes: 15,
    ingredients: [
      "2 tranches pain complet",
      "2 œufs",
      "60g saumon fumé",
      "Quelques brins d'aneth, citron",
    ],
    steps: [
      "Pocher les œufs 3 min dans l'eau frémissante avec un trait de vinaigre.",
      "Griller le pain, déposer le saumon fumé dessus.",
      "Ajouter l'œuf poché, l'aneth et un filet de citron.",
    ],
    favorite: false,
  },
  {
    id: "seed-13",
    name: "Poulet teriyaki maison, riz & edamame",
    category: "dejeuner",
    kcal: 550,
    protein: 42,
    carbs: 60,
    fat: 13,
    prepMinutes: 25,
    ingredients: [
      "150g blanc de poulet",
      "80g riz (poids cru)",
      "80g edamame écossés",
      "Sauce soja, miel, ail, gingembre",
    ],
    steps: [
      "Préparer la sauce teriyaki : soja, un filet de miel, ail et gingembre.",
      "Cuire le poulet à la poêle puis napper de sauce en fin de cuisson.",
      "Servir avec le riz cuit et les edamame vapeur.",
    ],
    favorite: false,
  },
  {
    id: "seed-14",
    name: "Buddha bowl pois chiches rôtis & tahini",
    category: "dejeuner",
    kcal: 500,
    protein: 20,
    carbs: 58,
    fat: 20,
    prepMinutes: 30,
    ingredients: [
      "150g pois chiches cuits",
      "1 patate douce",
      "Épinards ou roquette",
      "1 c. à s. tahini, citron, cumin",
    ],
    steps: [
      "Rôtir les pois chiches et la patate douce en dés au four avec cumin (20 min, 200°C).",
      "Préparer la sauce tahini-citron.",
      "Assembler sur un lit de verdure et napper de sauce.",
    ],
    favorite: false,
  },
  {
    id: "seed-15",
    name: "Bœuf haché 5%, patate douce & haricots verts",
    category: "diner",
    kcal: 520,
    protein: 42,
    carbs: 40,
    fat: 16,
    prepMinutes: 25,
    ingredients: [
      "150g bœuf haché 5% MG",
      "1 patate douce",
      "150g haricots verts",
      "Ail, thym, huile d'olive",
    ],
    steps: [
      "Cuire la patate douce au four ou à la vapeur.",
      "Poêler le bœuf haché avec ail et thym.",
      "Cuire les haricots verts à la vapeur, assembler le tout.",
    ],
    favorite: false,
  },
  {
    id: "seed-16",
    name: "Cabillaud vapeur, riz complet & légumes wok",
    category: "diner",
    kcal: 450,
    protein: 38,
    carbs: 50,
    fat: 9,
    prepMinutes: 25,
    ingredients: [
      "150g filet de cabillaud",
      "70g riz complet (poids cru)",
      "Poivron, carotte, brocolis",
      "Sauce soja, gingembre",
    ],
    steps: [
      "Cuire le cabillaud à la vapeur 10-12 min.",
      "Faire sauter les légumes au wok avec gingembre et sauce soja.",
      "Servir avec le riz complet.",
    ],
    favorite: false,
  },
  {
    id: "seed-17",
    name: "Chili con carne allégé",
    category: "diner",
    kcal: 490,
    protein: 38,
    carbs: 45,
    fat: 15,
    prepMinutes: 35,
    ingredients: [
      "150g bœuf ou dinde hachée",
      "150g haricots rouges cuits",
      "Tomates concassées, oignon, poivron",
      "Épices chili, cumin, paprika",
    ],
    steps: [
      "Faire revenir la viande avec oignon et poivron.",
      "Ajouter tomates, haricots rouges et épices.",
      "Laisser mijoter 20-25 min à couvert.",
    ],
    favorite: false,
  },
  {
    id: "seed-18",
    name: "Pâtes complètes, poulet & pesto maison",
    category: "diner",
    kcal: 560,
    protein: 38,
    carbs: 62,
    fat: 16,
    prepMinutes: 20,
    ingredients: [
      "80g pâtes complètes (poids cru)",
      "150g blanc de poulet",
      "Basilic, ail, parmesan, huile d'olive",
      "Pignons ou noix",
    ],
    steps: [
      "Cuire les pâtes al dente.",
      "Griller le poulet en lamelles.",
      "Mixer basilic, ail, parmesan, huile et pignons pour le pesto, mélanger le tout.",
    ],
    favorite: false,
  },
  {
    id: "seed-19",
    name: "Barres protéinées maison flocons-cacahuète",
    category: "collation",
    kcal: 220,
    protein: 14,
    carbs: 22,
    fat: 9,
    prepMinutes: 15,
    ingredients: [
      "100g flocons d'avoine",
      "2 c. à s. beurre de cacahuète",
      "1 scoop whey",
      "Miel, un peu de lait",
    ],
    steps: [
      "Mélanger tous les ingrédients jusqu'à obtenir une pâte homogène.",
      "Étaler dans un moule, tasser fermement.",
      "Réfrigérer 1h puis découper en barres.",
    ],
    favorite: false,
  },
  {
    id: "seed-20",
    name: "Fromage blanc, miel & noix",
    category: "collation",
    kcal: 260,
    protein: 18,
    carbs: 22,
    fat: 12,
    prepMinutes: 3,
    ingredients: [
      "200g fromage blanc 20%",
      "1 c. à c. miel",
      "Une poignée de noix ou amandes",
    ],
    steps: [
      "Verser le fromage blanc dans un bol.",
      "Ajouter le miel et les noix concassées.",
    ],
    favorite: false,
  },
  {
    id: "seed-21",
    name: "Smoothie vert protéiné",
    category: "collation",
    kcal: 290,
    protein: 22,
    carbs: 34,
    fat: 6,
    prepMinutes: 5,
    ingredients: [
      "1 scoop whey vanille",
      "1 poignée d'épinards",
      "1 banane",
      "200ml lait ou boisson végétale",
    ],
    steps: [
      "Mixer tous les ingrédients jusqu'à consistance lisse.",
      "Servir immédiatement.",
    ],
    favorite: false,
  },
  {
    id: "seed-22",
    name: "Pommes au four, cannelle & amandes",
    category: "collation",
    kcal: 200,
    protein: 4,
    carbs: 32,
    fat: 7,
    prepMinutes: 25,
    ingredients: [
      "2 pommes",
      "Cannelle",
      "1 c. à s. amandes effilées",
      "Un filet de miel",
    ],
    steps: [
      "Évider les pommes, saupoudrer de cannelle.",
      "Cuire au four 20 min à 180°C.",
      "Ajouter amandes et miel en sortie de four.",
    ],
    favorite: false,
  },
  {
    id: "seed-23",
    name: "Bowl de récup' riz, poulet & légumes rôtis",
    category: "post-training",
    kcal: 480,
    protein: 40,
    carbs: 55,
    fat: 10,
    prepMinutes: 25,
    ingredients: [
      "150g blanc de poulet",
      "70g riz blanc (poids cru, digestion rapide)",
      "Courgette et poivron rôtis",
      "Sel, herbes de Provence",
    ],
    steps: [
      "Cuire le riz blanc.",
      "Rôtir les légumes au four avec un filet d'huile.",
      "Griller le poulet, assembler le tout — idéal dans l'heure suivant l'entraînement.",
    ],
    favorite: false,
  },
  {
    id: "seed-24",
    name: "Smoothie banane-cacao post-training",
    category: "post-training",
    kcal: 320,
    protein: 28,
    carbs: 40,
    fat: 6,
    prepMinutes: 5,
    ingredients: [
      "1 scoop whey chocolat",
      "1 banane",
      "1 c. à c. cacao non sucré",
      "250ml lait écrémé",
    ],
    steps: [
      "Mixer tous les ingrédients.",
      "Boire dans les 30-45 min après la séance.",
    ],
    favorite: false,
  },
  {
    id: "seed-25",
    name: "Riz au lait protéiné (version rapide)",
    category: "post-training",
    kcal: 340,
    protein: 24,
    carbs: 48,
    fat: 6,
    prepMinutes: 15,
    ingredients: [
      "60g riz rond",
      "300ml lait écrémé",
      "1 scoop whey vanille (hors du feu)",
      "Cannelle",
    ],
    steps: [
      "Cuire le riz dans le lait à feu doux 12-15 min en remuant.",
      "Laisser tiédir, puis incorporer la whey hors du feu.",
      "Saupoudrer de cannelle.",
    ],
    favorite: false,
  },
];
