import { Recipe } from "./types";

// Recettes healthy de base, orientées pratiquant de JJB (riche en protéines,
// bon équilibre glucides/lipides, pensées pour la récup' et la gestion de poids).
export const SEED_RECIPES: Recipe[] = [
  {
    id: "seed-1",
    name: "Bowl poulet, riz complet & brocolis",
    category: "dejeuner",
    kcal: 520,
    protein: 45,
    carbs: 55,
    fat: 12,
    prepMinutes: 25,
    ingredients: [
      "150g blanc de poulet",
      "80g riz complet (poids cru)",
      "150g brocolis",
      "1 c. à s. huile d'olive",
      "Sauce soja, ail, gingembre",
    ],
    steps: [
      "Cuire le riz complet.",
      "Faire revenir le poulet coupé en dés avec ail et gingembre.",
      "Cuire les brocolis à la vapeur 5-7 min.",
      "Assembler dans un bowl, arroser de sauce soja et d'un filet d'huile d'olive.",
    ],
    favorite: false,
  },
  {
    id: "seed-2",
    name: "Porridge protéiné banane-amande",
    category: "petit-dejeuner",
    kcal: 420,
    protein: 28,
    carbs: 50,
    fat: 12,
    prepMinutes: 10,
    ingredients: [
      "50g flocons d'avoine",
      "1 scoop whey vanille",
      "1 banane",
      "200ml lait d'amande",
      "1 c. à s. beurre d'amande",
    ],
    steps: [
      "Faire chauffer le lait d'amande avec les flocons d'avoine 5 min.",
      "Retirer du feu, incorporer la whey une fois tiède.",
      "Ajouter la banane en rondelles et le beurre d'amande.",
    ],
    favorite: false,
  },
  {
    id: "seed-3",
    name: "Saumon grillé, patate douce & épinards",
    category: "diner",
    kcal: 560,
    protein: 40,
    carbs: 45,
    fat: 20,
    prepMinutes: 30,
    ingredients: [
      "150g pavé de saumon",
      "1 patate douce moyenne",
      "100g épinards frais",
      "Citron, huile d'olive, sel, poivre",
    ],
    steps: [
      "Couper la patate douce en cubes, cuire au four 25 min à 200°C.",
      "Poêler le saumon 4 min de chaque côté.",
      "Faire tomber les épinards à la poêle avec un filet d'huile.",
      "Dresser avec un trait de citron.",
    ],
    favorite: false,
  },
  {
    id: "seed-4",
    name: "Shaker de récup' post-training",
    category: "post-training",
    kcal: 280,
    protein: 30,
    carbs: 35,
    fat: 4,
    prepMinutes: 5,
    ingredients: [
      "1 scoop whey",
      "1 banane",
      "250ml lait écrémé ou boisson végétale",
      "1 pincée de sel (électrolytes)",
    ],
    steps: [
      "Mixer tous les ingrédients.",
      "Boire dans les 30-45 min après la séance.",
    ],
    favorite: false,
  },
  {
    id: "seed-5",
    name: "Œufs brouillés, avocat & pain complet",
    category: "petit-dejeuner",
    kcal: 450,
    protein: 24,
    carbs: 30,
    fat: 24,
    prepMinutes: 12,
    ingredients: [
      "3 œufs",
      "1/2 avocat",
      "2 tranches pain complet",
      "Sel, poivre, piment doux",
    ],
    steps: [
      "Brouiller les œufs à feu doux.",
      "Griller le pain, écraser l'avocat dessus.",
      "Servir ensemble, assaisonner.",
    ],
    favorite: false,
  },
  {
    id: "seed-6",
    name: "Salade thon, quinoa & pois chiches",
    category: "dejeuner",
    kcal: 490,
    protein: 35,
    carbs: 48,
    fat: 15,
    prepMinutes: 15,
    ingredients: [
      "1 boîte de thon au naturel",
      "80g quinoa (poids cru)",
      "100g pois chiches cuits",
      "Concombre, tomate, huile d'olive, citron",
    ],
    steps: [
      "Cuire le quinoa selon le paquet, laisser refroidir.",
      "Mélanger avec le thon égoutté, les pois chiches et les légumes coupés.",
      "Assaisonner avec huile d'olive et citron.",
    ],
    favorite: false,
  },
  {
    id: "seed-7",
    name: "Wrap dinde, crudités & houmous",
    category: "collation",
    kcal: 350,
    protein: 25,
    carbs: 35,
    fat: 12,
    prepMinutes: 8,
    ingredients: [
      "1 tortilla complète",
      "80g blanc de dinde tranché",
      "2 c. à s. houmous",
      "Carotte râpée, salade, concombre",
    ],
    steps: [
      "Étaler le houmous sur la tortilla.",
      "Garnir de dinde et de crudités.",
      "Rouler serré et couper en deux.",
    ],
    favorite: false,
  },
  {
    id: "seed-8",
    name: "Yaourt grec, fruits rouges & granola maison",
    category: "collation",
    kcal: 300,
    protein: 20,
    carbs: 32,
    fat: 9,
    prepMinutes: 5,
    ingredients: [
      "200g yaourt grec 0-2%",
      "100g fruits rouges (frais ou surgelés)",
      "30g granola peu sucré",
      "1 filet de miel (optionnel)",
    ],
    steps: [
      "Verser le yaourt dans un bol.",
      "Ajouter les fruits rouges et le granola.",
      "Filet de miel en option.",
    ],
    favorite: false,
  },
  {
    id: "seed-9",
    name: "Curry de lentilles corail & riz basmati",
    category: "diner",
    kcal: 480,
    protein: 22,
    carbs: 70,
    fat: 12,
    prepMinutes: 30,
    ingredients: [
      "150g lentilles corail",
      "70g riz basmati (poids cru)",
      "Lait de coco léger, curry, oignon, ail",
      "Épinards ou tomates",
    ],
    steps: [
      "Faire revenir oignon et ail, ajouter le curry.",
      "Ajouter les lentilles, le lait de coco et un peu d'eau, cuire 20 min.",
      "Servir avec le riz basmati cuit.",
    ],
    favorite: false,
  },
  {
    id: "seed-10",
    name: "Omelette blanche aux légumes",
    category: "post-training",
    kcal: 310,
    protein: 32,
    carbs: 12,
    fat: 14,
    prepMinutes: 12,
    ingredients: [
      "5 blancs d'œufs + 1 œuf entier",
      "Poivron, champignons, épinards",
      "1 c. à c. huile d'olive",
    ],
    steps: [
      "Faire revenir les légumes émincés.",
      "Ajouter les œufs battus, cuire à feu doux en pliant l'omelette.",
    ],
    favorite: false,
  },
];
